//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591

namespace Radzen.Blazor {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RadzenStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadzenStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radzen.Blazor.RadzenStrings", typeof(RadzenStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Spreadsheet_FileTab { get { return ResourceManager.GetString("Spreadsheet_FileTab", resourceCulture); } }
        public static string Spreadsheet_HomeTab { get { return ResourceManager.GetString("Spreadsheet_HomeTab", resourceCulture); } }
        public static string Spreadsheet_FormatTab { get { return ResourceManager.GetString("Spreadsheet_FormatTab", resourceCulture); } }
        public static string Spreadsheet_InsertTab { get { return ResourceManager.GetString("Spreadsheet_InsertTab", resourceCulture); } }
        public static string Spreadsheet_ViewTab { get { return ResourceManager.GetString("Spreadsheet_ViewTab", resourceCulture); } }
        public static string Spreadsheet_DataTab { get { return ResourceManager.GetString("Spreadsheet_DataTab", resourceCulture); } }
        public static string Spreadsheet_OK { get { return ResourceManager.GetString("Spreadsheet_OK", resourceCulture); } }
        public static string Spreadsheet_Cancel { get { return ResourceManager.GetString("Spreadsheet_Cancel", resourceCulture); } }
        public static string Spreadsheet_FormatCells { get { return ResourceManager.GetString("Spreadsheet_FormatCells", resourceCulture); } }
        public static string Spreadsheet_Rename { get { return ResourceManager.GetString("Spreadsheet_Rename", resourceCulture); } }
        public static string Spreadsheet_Delete { get { return ResourceManager.GetString("Spreadsheet_Delete", resourceCulture); } }
        public static string Spreadsheet_MoveLeft { get { return ResourceManager.GetString("Spreadsheet_MoveLeft", resourceCulture); } }
        public static string Spreadsheet_MoveRight { get { return ResourceManager.GetString("Spreadsheet_MoveRight", resourceCulture); } }
        public static string Spreadsheet_SortAscending { get { return ResourceManager.GetString("Spreadsheet_SortAscending", resourceCulture); } }
        public static string Spreadsheet_SortDescending { get { return ResourceManager.GetString("Spreadsheet_SortDescending", resourceCulture); } }
        public static string Spreadsheet_ClearFilter { get { return ResourceManager.GetString("Spreadsheet_ClearFilter", resourceCulture); } }
        public static string Spreadsheet_CustomFilter { get { return ResourceManager.GetString("Spreadsheet_CustomFilter", resourceCulture); } }
        public static string Spreadsheet_SelectAll { get { return ResourceManager.GetString("Spreadsheet_SelectAll", resourceCulture); } }
        public static string Spreadsheet_Blank { get { return ResourceManager.GetString("Spreadsheet_Blank", resourceCulture); } }
        public static string Spreadsheet_Cut { get { return ResourceManager.GetString("Spreadsheet_Cut", resourceCulture); } }
        public static string Spreadsheet_Copy { get { return ResourceManager.GetString("Spreadsheet_Copy", resourceCulture); } }
        public static string Spreadsheet_Paste { get { return ResourceManager.GetString("Spreadsheet_Paste", resourceCulture); } }
        public static string Spreadsheet_ClearContents { get { return ResourceManager.GetString("Spreadsheet_ClearContents", resourceCulture); } }
        public static string Spreadsheet_ContextSortAscending { get { return ResourceManager.GetString("Spreadsheet_ContextSortAscending", resourceCulture); } }
        public static string Spreadsheet_ContextSortDescending { get { return ResourceManager.GetString("Spreadsheet_ContextSortDescending", resourceCulture); } }
        public static string Spreadsheet_InsertRowAbove { get { return ResourceManager.GetString("Spreadsheet_InsertRowAbove", resourceCulture); } }
        public static string Spreadsheet_InsertRowBelow { get { return ResourceManager.GetString("Spreadsheet_InsertRowBelow", resourceCulture); } }
        public static string Spreadsheet_DeleteRow { get { return ResourceManager.GetString("Spreadsheet_DeleteRow", resourceCulture); } }
        public static string Spreadsheet_HideRow { get { return ResourceManager.GetString("Spreadsheet_HideRow", resourceCulture); } }
        public static string Spreadsheet_UnhideRow { get { return ResourceManager.GetString("Spreadsheet_UnhideRow", resourceCulture); } }
        public static string Spreadsheet_InsertColumnBefore { get { return ResourceManager.GetString("Spreadsheet_InsertColumnBefore", resourceCulture); } }
        public static string Spreadsheet_InsertColumnAfter { get { return ResourceManager.GetString("Spreadsheet_InsertColumnAfter", resourceCulture); } }
        public static string Spreadsheet_DeleteColumn { get { return ResourceManager.GetString("Spreadsheet_DeleteColumn", resourceCulture); } }
        public static string Spreadsheet_HideColumn { get { return ResourceManager.GetString("Spreadsheet_HideColumn", resourceCulture); } }
        public static string Spreadsheet_UnhideColumn { get { return ResourceManager.GetString("Spreadsheet_UnhideColumn", resourceCulture); } }
        public static string Spreadsheet_RenameSheetTitle { get { return ResourceManager.GetString("Spreadsheet_RenameSheetTitle", resourceCulture); } }
        public static string Spreadsheet_CustomFilterTitle { get { return ResourceManager.GetString("Spreadsheet_CustomFilterTitle", resourceCulture); } }
        public static string Spreadsheet_FormatCellsTitle { get { return ResourceManager.GetString("Spreadsheet_FormatCellsTitle", resourceCulture); } }
        public static string Spreadsheet_InsertHyperlinkTitle { get { return ResourceManager.GetString("Spreadsheet_InsertHyperlinkTitle", resourceCulture); } }
        public static string Spreadsheet_ConditionalFormattingTitle { get { return ResourceManager.GetString("Spreadsheet_ConditionalFormattingTitle", resourceCulture); } }
        public static string Spreadsheet_DataValidationTitle { get { return ResourceManager.GetString("Spreadsheet_DataValidationTitle", resourceCulture); } }
        public static string Spreadsheet_InformationTitle { get { return ResourceManager.GetString("Spreadsheet_InformationTitle", resourceCulture); } }
        public static string Spreadsheet_WarningTitle { get { return ResourceManager.GetString("Spreadsheet_WarningTitle", resourceCulture); } }
        public static string Spreadsheet_InvalidValueTitle { get { return ResourceManager.GetString("Spreadsheet_InvalidValueTitle", resourceCulture); } }
        public static string Spreadsheet_DoYouWantToContinue { get { return ResourceManager.GetString("Spreadsheet_DoYouWantToContinue", resourceCulture); } }
        public static string Spreadsheet_NameCannotBeEmpty { get { return ResourceManager.GetString("Spreadsheet_NameCannotBeEmpty", resourceCulture); } }
        public static string Spreadsheet_SheetNameAlreadyExists { get { return ResourceManager.GetString("Spreadsheet_SheetNameAlreadyExists", resourceCulture); } }
        public static string Spreadsheet_DefaultValidationError { get { return ResourceManager.GetString("Spreadsheet_DefaultValidationError", resourceCulture); } }
        public static string Spreadsheet_ShowRowsWhere { get { return ResourceManager.GetString("Spreadsheet_ShowRowsWhere", resourceCulture); } }
        public static string Spreadsheet_SelectOperator { get { return ResourceManager.GetString("Spreadsheet_SelectOperator", resourceCulture); } }
        public static string Spreadsheet_EnterValue { get { return ResourceManager.GetString("Spreadsheet_EnterValue", resourceCulture); } }
        public static string Spreadsheet_ColumnFormat { get { return ResourceManager.GetString("Spreadsheet_ColumnFormat", resourceCulture); } }
        public static string Spreadsheet_FilterEquals { get { return ResourceManager.GetString("Spreadsheet_FilterEquals", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotEqual { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotEqual", resourceCulture); } }
        public static string Spreadsheet_FilterGreaterThan { get { return ResourceManager.GetString("Spreadsheet_FilterGreaterThan", resourceCulture); } }
        public static string Spreadsheet_FilterGreaterThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_FilterGreaterThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_FilterLessThan { get { return ResourceManager.GetString("Spreadsheet_FilterLessThan", resourceCulture); } }
        public static string Spreadsheet_FilterLessThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_FilterLessThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_FilterBeginsWith { get { return ResourceManager.GetString("Spreadsheet_FilterBeginsWith", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotBeginWith { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotBeginWith", resourceCulture); } }
        public static string Spreadsheet_FilterEndsWith { get { return ResourceManager.GetString("Spreadsheet_FilterEndsWith", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotEndWith { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotEndWith", resourceCulture); } }
        public static string Spreadsheet_FilterContains { get { return ResourceManager.GetString("Spreadsheet_FilterContains", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotContain { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotContain", resourceCulture); } }
        public static string Spreadsheet_FilterIsEmpty { get { return ResourceManager.GetString("Spreadsheet_FilterIsEmpty", resourceCulture); } }
        public static string Spreadsheet_FilterIsNotEmpty { get { return ResourceManager.GetString("Spreadsheet_FilterIsNotEmpty", resourceCulture); } }
        public static string Spreadsheet_FilterAnd { get { return ResourceManager.GetString("Spreadsheet_FilterAnd", resourceCulture); } }
        public static string Spreadsheet_FilterOr { get { return ResourceManager.GetString("Spreadsheet_FilterOr", resourceCulture); } }
        public static string Spreadsheet_Sample { get { return ResourceManager.GetString("Spreadsheet_Sample", resourceCulture); } }
        public static string Spreadsheet_DecimalPlaces { get { return ResourceManager.GetString("Spreadsheet_DecimalPlaces", resourceCulture); } }
        public static string Spreadsheet_UseThousandsSeparator { get { return ResourceManager.GetString("Spreadsheet_UseThousandsSeparator", resourceCulture); } }
        public static string Spreadsheet_Symbol { get { return ResourceManager.GetString("Spreadsheet_Symbol", resourceCulture); } }
        public static string Spreadsheet_Type { get { return ResourceManager.GetString("Spreadsheet_Type", resourceCulture); } }
        public static string Spreadsheet_FormatCode { get { return ResourceManager.GetString("Spreadsheet_FormatCode", resourceCulture); } }
        public static string Spreadsheet_Conditional { get { return ResourceManager.GetString("Spreadsheet_Conditional", resourceCulture); } }
        public static string Spreadsheet_GreaterThanMenu { get { return ResourceManager.GetString("Spreadsheet_GreaterThanMenu", resourceCulture); } }
        public static string Spreadsheet_LessThanMenu { get { return ResourceManager.GetString("Spreadsheet_LessThanMenu", resourceCulture); } }
        public static string Spreadsheet_BetweenMenu { get { return ResourceManager.GetString("Spreadsheet_BetweenMenu", resourceCulture); } }
        public static string Spreadsheet_EqualToMenu { get { return ResourceManager.GetString("Spreadsheet_EqualToMenu", resourceCulture); } }
        public static string Spreadsheet_TextContainsMenu { get { return ResourceManager.GetString("Spreadsheet_TextContainsMenu", resourceCulture); } }
        public static string Spreadsheet_RuleType { get { return ResourceManager.GetString("Spreadsheet_RuleType", resourceCulture); } }
        public static string Spreadsheet_Value { get { return ResourceManager.GetString("Spreadsheet_Value", resourceCulture); } }
        public static string Spreadsheet_Minimum { get { return ResourceManager.GetString("Spreadsheet_Minimum", resourceCulture); } }
        public static string Spreadsheet_Maximum { get { return ResourceManager.GetString("Spreadsheet_Maximum", resourceCulture); } }
        public static string Spreadsheet_Text { get { return ResourceManager.GetString("Spreadsheet_Text", resourceCulture); } }
        public static string Spreadsheet_BackgroundColor { get { return ResourceManager.GetString("Spreadsheet_BackgroundColor", resourceCulture); } }
        public static string Spreadsheet_TextColor { get { return ResourceManager.GetString("Spreadsheet_TextColor", resourceCulture); } }
        public static string Spreadsheet_RuleGreaterThan { get { return ResourceManager.GetString("Spreadsheet_RuleGreaterThan", resourceCulture); } }
        public static string Spreadsheet_RuleLessThan { get { return ResourceManager.GetString("Spreadsheet_RuleLessThan", resourceCulture); } }
        public static string Spreadsheet_RuleBetween { get { return ResourceManager.GetString("Spreadsheet_RuleBetween", resourceCulture); } }
        public static string Spreadsheet_RuleEqualTo { get { return ResourceManager.GetString("Spreadsheet_RuleEqualTo", resourceCulture); } }
        public static string Spreadsheet_RuleTextContains { get { return ResourceManager.GetString("Spreadsheet_RuleTextContains", resourceCulture); } }
        public static string Spreadsheet_Validation { get { return ResourceManager.GetString("Spreadsheet_Validation", resourceCulture); } }
        public static string Spreadsheet_DataValidationMenu { get { return ResourceManager.GetString("Spreadsheet_DataValidationMenu", resourceCulture); } }
        public static string Spreadsheet_ClearValidation { get { return ResourceManager.GetString("Spreadsheet_ClearValidation", resourceCulture); } }
        public static string Spreadsheet_ValidationType { get { return ResourceManager.GetString("Spreadsheet_ValidationType", resourceCulture); } }
        public static string Spreadsheet_Operator { get { return ResourceManager.GetString("Spreadsheet_Operator", resourceCulture); } }
        public static string Spreadsheet_Formula { get { return ResourceManager.GetString("Spreadsheet_Formula", resourceCulture); } }
        public static string Spreadsheet_ValuesCommaSeparated { get { return ResourceManager.GetString("Spreadsheet_ValuesCommaSeparated", resourceCulture); } }
        public static string Spreadsheet_AllowBlank { get { return ResourceManager.GetString("Spreadsheet_AllowBlank", resourceCulture); } }
        public static string Spreadsheet_ErrorAlert { get { return ResourceManager.GetString("Spreadsheet_ErrorAlert", resourceCulture); } }
        public static string Spreadsheet_Style { get { return ResourceManager.GetString("Spreadsheet_Style", resourceCulture); } }
        public static string Spreadsheet_Title { get { return ResourceManager.GetString("Spreadsheet_Title", resourceCulture); } }
        public static string Spreadsheet_Message { get { return ResourceManager.GetString("Spreadsheet_Message", resourceCulture); } }
        public static string Spreadsheet_InputPrompt { get { return ResourceManager.GetString("Spreadsheet_InputPrompt", resourceCulture); } }
        public static string Spreadsheet_ShowInputMessage { get { return ResourceManager.GetString("Spreadsheet_ShowInputMessage", resourceCulture); } }
        public static string Spreadsheet_ValidationWholeNumber { get { return ResourceManager.GetString("Spreadsheet_ValidationWholeNumber", resourceCulture); } }
        public static string Spreadsheet_ValidationDecimal { get { return ResourceManager.GetString("Spreadsheet_ValidationDecimal", resourceCulture); } }
        public static string Spreadsheet_ValidationList { get { return ResourceManager.GetString("Spreadsheet_ValidationList", resourceCulture); } }
        public static string Spreadsheet_ValidationDate { get { return ResourceManager.GetString("Spreadsheet_ValidationDate", resourceCulture); } }
        public static string Spreadsheet_ValidationTime { get { return ResourceManager.GetString("Spreadsheet_ValidationTime", resourceCulture); } }
        public static string Spreadsheet_ValidationTextLength { get { return ResourceManager.GetString("Spreadsheet_ValidationTextLength", resourceCulture); } }
        public static string Spreadsheet_ValidationCustom { get { return ResourceManager.GetString("Spreadsheet_ValidationCustom", resourceCulture); } }
        public static string Spreadsheet_OperatorBetween { get { return ResourceManager.GetString("Spreadsheet_OperatorBetween", resourceCulture); } }
        public static string Spreadsheet_OperatorNotBetween { get { return ResourceManager.GetString("Spreadsheet_OperatorNotBetween", resourceCulture); } }
        public static string Spreadsheet_OperatorEqualTo { get { return ResourceManager.GetString("Spreadsheet_OperatorEqualTo", resourceCulture); } }
        public static string Spreadsheet_OperatorNotEqualTo { get { return ResourceManager.GetString("Spreadsheet_OperatorNotEqualTo", resourceCulture); } }
        public static string Spreadsheet_OperatorGreaterThan { get { return ResourceManager.GetString("Spreadsheet_OperatorGreaterThan", resourceCulture); } }
        public static string Spreadsheet_OperatorLessThan { get { return ResourceManager.GetString("Spreadsheet_OperatorLessThan", resourceCulture); } }
        public static string Spreadsheet_OperatorGreaterThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_OperatorGreaterThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_OperatorLessThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_OperatorLessThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_ErrorStyleStop { get { return ResourceManager.GetString("Spreadsheet_ErrorStyleStop", resourceCulture); } }
        public static string Spreadsheet_ErrorStyleWarning { get { return ResourceManager.GetString("Spreadsheet_ErrorStyleWarning", resourceCulture); } }
        public static string Spreadsheet_ErrorStyleInformation { get { return ResourceManager.GetString("Spreadsheet_ErrorStyleInformation", resourceCulture); } }
        public static string Spreadsheet_FreezePanes { get { return ResourceManager.GetString("Spreadsheet_FreezePanes", resourceCulture); } }
        public static string Spreadsheet_FreezeTopRow { get { return ResourceManager.GetString("Spreadsheet_FreezeTopRow", resourceCulture); } }
        public static string Spreadsheet_FreezeSelectedRows { get { return ResourceManager.GetString("Spreadsheet_FreezeSelectedRows", resourceCulture); } }
        public static string Spreadsheet_FreezeFirstColumn { get { return ResourceManager.GetString("Spreadsheet_FreezeFirstColumn", resourceCulture); } }
        public static string Spreadsheet_FreezeSelectedColumns { get { return ResourceManager.GetString("Spreadsheet_FreezeSelectedColumns", resourceCulture); } }
        public static string Spreadsheet_Unfreeze { get { return ResourceManager.GetString("Spreadsheet_Unfreeze", resourceCulture); } }
        public static string Spreadsheet_MergeAndCenter { get { return ResourceManager.GetString("Spreadsheet_MergeAndCenter", resourceCulture); } }
        public static string Spreadsheet_MergeCells { get { return ResourceManager.GetString("Spreadsheet_MergeCells", resourceCulture); } }
        public static string Spreadsheet_UnmergeCells { get { return ResourceManager.GetString("Spreadsheet_UnmergeCells", resourceCulture); } }
        public static string Spreadsheet_AllBorders { get { return ResourceManager.GetString("Spreadsheet_AllBorders", resourceCulture); } }
        public static string Spreadsheet_OutsideBorders { get { return ResourceManager.GetString("Spreadsheet_OutsideBorders", resourceCulture); } }
        public static string Spreadsheet_TopBorder { get { return ResourceManager.GetString("Spreadsheet_TopBorder", resourceCulture); } }
        public static string Spreadsheet_BottomBorder { get { return ResourceManager.GetString("Spreadsheet_BottomBorder", resourceCulture); } }
        public static string Spreadsheet_LeftBorder { get { return ResourceManager.GetString("Spreadsheet_LeftBorder", resourceCulture); } }
        public static string Spreadsheet_RightBorder { get { return ResourceManager.GetString("Spreadsheet_RightBorder", resourceCulture); } }
        public static string Spreadsheet_NoBorder { get { return ResourceManager.GetString("Spreadsheet_NoBorder", resourceCulture); } }
        public static string Spreadsheet_FormatGeneral { get { return ResourceManager.GetString("Spreadsheet_FormatGeneral", resourceCulture); } }
        public static string Spreadsheet_FormatNumber { get { return ResourceManager.GetString("Spreadsheet_FormatNumber", resourceCulture); } }
        public static string Spreadsheet_FormatCurrency { get { return ResourceManager.GetString("Spreadsheet_FormatCurrency", resourceCulture); } }
        public static string Spreadsheet_FormatAccounting { get { return ResourceManager.GetString("Spreadsheet_FormatAccounting", resourceCulture); } }
        public static string Spreadsheet_FormatPercentage { get { return ResourceManager.GetString("Spreadsheet_FormatPercentage", resourceCulture); } }
        public static string Spreadsheet_FormatScientific { get { return ResourceManager.GetString("Spreadsheet_FormatScientific", resourceCulture); } }
        public static string Spreadsheet_FormatDate { get { return ResourceManager.GetString("Spreadsheet_FormatDate", resourceCulture); } }
        public static string Spreadsheet_FormatTime { get { return ResourceManager.GetString("Spreadsheet_FormatTime", resourceCulture); } }
        public static string Spreadsheet_FormatText { get { return ResourceManager.GetString("Spreadsheet_FormatText", resourceCulture); } }
        public static string Spreadsheet_URL { get { return ResourceManager.GetString("Spreadsheet_URL", resourceCulture); } }
        public static string Spreadsheet_DisplayText { get { return ResourceManager.GetString("Spreadsheet_DisplayText", resourceCulture); } }
        public static string Spreadsheet_IncreaseDecimalPlaces { get { return ResourceManager.GetString("Spreadsheet_IncreaseDecimalPlaces", resourceCulture); } }
        public static string Spreadsheet_DecreaseDecimalPlaces { get { return ResourceManager.GetString("Spreadsheet_DecreaseDecimalPlaces", resourceCulture); } }
        public static string Spreadsheet_EditChart { get { return ResourceManager.GetString("Spreadsheet_EditChart", resourceCulture); } }
        public static string Spreadsheet_DeleteChart { get { return ResourceManager.GetString("Spreadsheet_DeleteChart", resourceCulture); } }
        public static string Spreadsheet_EditChartTitle { get { return ResourceManager.GetString("Spreadsheet_EditChartTitle", resourceCulture); } }
        public static string Spreadsheet_ChartType { get { return ResourceManager.GetString("Spreadsheet_ChartType", resourceCulture); } }
        public static string Spreadsheet_ChartTitle { get { return ResourceManager.GetString("Spreadsheet_ChartTitle", resourceCulture); } }
        public static string Spreadsheet_ShowLegend { get { return ResourceManager.GetString("Spreadsheet_ShowLegend", resourceCulture); } }
        public static string Spreadsheet_LegendPosition { get { return ResourceManager.GetString("Spreadsheet_LegendPosition", resourceCulture); } }
        public static string Spreadsheet_Series { get { return ResourceManager.GetString("Spreadsheet_Series", resourceCulture); } }
        public static string Spreadsheet_SeriesColor { get { return ResourceManager.GetString("Spreadsheet_SeriesColor", resourceCulture); } }
        public static string Spreadsheet_CategoryRange { get { return ResourceManager.GetString("Spreadsheet_CategoryRange", resourceCulture); } }
        public static string Spreadsheet_ValueRange { get { return ResourceManager.GetString("Spreadsheet_ValueRange", resourceCulture); } }
        public static string Spreadsheet_SeriesTitle { get { return ResourceManager.GetString("Spreadsheet_SeriesTitle", resourceCulture); } }
        public static string Spreadsheet_AddSeries { get { return ResourceManager.GetString("Spreadsheet_AddSeries", resourceCulture); } }
        public static string Spreadsheet_InsertHyperlink { get { return ResourceManager.GetString("Spreadsheet_InsertHyperlink", resourceCulture); } }
        public static string Spreadsheet_InsertImage { get { return ResourceManager.GetString("Spreadsheet_InsertImage", resourceCulture); } }
        public static string Spreadsheet_InsertChart { get { return ResourceManager.GetString("Spreadsheet_InsertChart", resourceCulture); } }
        public static string Spreadsheet_InsertTable { get { return ResourceManager.GetString("Spreadsheet_InsertTable", resourceCulture); } }
        public static string Spreadsheet_TableName { get { return ResourceManager.GetString("Spreadsheet_TableName", resourceCulture); } }
        public static string Spreadsheet_TableHasHeaders { get { return ResourceManager.GetString("Spreadsheet_TableHasHeaders", resourceCulture); } }
        public static string Spreadsheet_TableRange { get { return ResourceManager.GetString("Spreadsheet_TableRange", resourceCulture); } }
        public static string Spreadsheet_TableDesignTab { get { return ResourceManager.GetString("Spreadsheet_TableDesignTab", resourceCulture); } }
        public static string Spreadsheet_TableDesignName { get { return ResourceManager.GetString("Spreadsheet_TableDesignName", resourceCulture); } }
        public static string Spreadsheet_TableDesignStyle { get { return ResourceManager.GetString("Spreadsheet_TableDesignStyle", resourceCulture); } }
        public static string Spreadsheet_TableDesignHeader { get { return ResourceManager.GetString("Spreadsheet_TableDesignHeader", resourceCulture); } }
        public static string Spreadsheet_TableDesignTotals { get { return ResourceManager.GetString("Spreadsheet_TableDesignTotals", resourceCulture); } }
        public static string Spreadsheet_TableDesignFilter { get { return ResourceManager.GetString("Spreadsheet_TableDesignFilter", resourceCulture); } }
        public static string Spreadsheet_TableDesignBandedRows { get { return ResourceManager.GetString("Spreadsheet_TableDesignBandedRows", resourceCulture); } }
        public static string Spreadsheet_TableDesignBandedColumns { get { return ResourceManager.GetString("Spreadsheet_TableDesignBandedColumns", resourceCulture); } }
        public static string Spreadsheet_TableDesignFirstColumn { get { return ResourceManager.GetString("Spreadsheet_TableDesignFirstColumn", resourceCulture); } }
        public static string Spreadsheet_TableDesignLastColumn { get { return ResourceManager.GetString("Spreadsheet_TableDesignLastColumn", resourceCulture); } }
        public static string Spreadsheet_TableDesignTotalsForColumn { get { return ResourceManager.GetString("Spreadsheet_TableDesignTotalsForColumn", resourceCulture); } }
        public static string Spreadsheet_ConvertTableToRange { get { return ResourceManager.GetString("Spreadsheet_ConvertTableToRange", resourceCulture); } }
        public static string Spreadsheet_DeleteTable { get { return ResourceManager.GetString("Spreadsheet_DeleteTable", resourceCulture); } }
        public static string Spreadsheet_TotalsNone { get { return ResourceManager.GetString("Spreadsheet_TotalsNone", resourceCulture); } }
        public static string Spreadsheet_TotalsSum { get { return ResourceManager.GetString("Spreadsheet_TotalsSum", resourceCulture); } }
        public static string Spreadsheet_TotalsAverage { get { return ResourceManager.GetString("Spreadsheet_TotalsAverage", resourceCulture); } }
        public static string Spreadsheet_TotalsCount { get { return ResourceManager.GetString("Spreadsheet_TotalsCount", resourceCulture); } }
        public static string Spreadsheet_TotalsCountNumbers { get { return ResourceManager.GetString("Spreadsheet_TotalsCountNumbers", resourceCulture); } }
        public static string Spreadsheet_TotalsMin { get { return ResourceManager.GetString("Spreadsheet_TotalsMin", resourceCulture); } }
        public static string Spreadsheet_TotalsMax { get { return ResourceManager.GetString("Spreadsheet_TotalsMax", resourceCulture); } }
        public static string Spreadsheet_TotalsStdDev { get { return ResourceManager.GetString("Spreadsheet_TotalsStdDev", resourceCulture); } }
        public static string Spreadsheet_TotalsVar { get { return ResourceManager.GetString("Spreadsheet_TotalsVar", resourceCulture); } }
        public static string Spreadsheet_CustomSort { get { return ResourceManager.GetString("Spreadsheet_CustomSort", resourceCulture); } }
        public static string Spreadsheet_CustomSortTooltip { get { return ResourceManager.GetString("Spreadsheet_CustomSortTooltip", resourceCulture); } }
        public static string Spreadsheet_SortHasHeaders { get { return ResourceManager.GetString("Spreadsheet_SortHasHeaders", resourceCulture); } }
        public static string Spreadsheet_SortLevelColumn { get { return ResourceManager.GetString("Spreadsheet_SortLevelColumn", resourceCulture); } }
        public static string Spreadsheet_SortLevelSortOn { get { return ResourceManager.GetString("Spreadsheet_SortLevelSortOn", resourceCulture); } }
        public static string Spreadsheet_SortLevelOrder { get { return ResourceManager.GetString("Spreadsheet_SortLevelOrder", resourceCulture); } }
        public static string Spreadsheet_SortLevelCustomList { get { return ResourceManager.GetString("Spreadsheet_SortLevelCustomList", resourceCulture); } }
        public static string Spreadsheet_SortLevelCustomListPlaceholder { get { return ResourceManager.GetString("Spreadsheet_SortLevelCustomListPlaceholder", resourceCulture); } }
        public static string Spreadsheet_SortLevelCase { get { return ResourceManager.GetString("Spreadsheet_SortLevelCase", resourceCulture); } }
        public static string Spreadsheet_SortLevelAddLevel { get { return ResourceManager.GetString("Spreadsheet_SortLevelAddLevel", resourceCulture); } }
        public static string Spreadsheet_SortOnValues { get { return ResourceManager.GetString("Spreadsheet_SortOnValues", resourceCulture); } }
        public static string Spreadsheet_SortOnCellColor { get { return ResourceManager.GetString("Spreadsheet_SortOnCellColor", resourceCulture); } }
        public static string Spreadsheet_SortOnFontColor { get { return ResourceManager.GetString("Spreadsheet_SortOnFontColor", resourceCulture); } }
        public static string Spreadsheet_SortOrderAscending { get { return ResourceManager.GetString("Spreadsheet_SortOrderAscending", resourceCulture); } }
        public static string Spreadsheet_SortOrderDescending { get { return ResourceManager.GetString("Spreadsheet_SortOrderDescending", resourceCulture); } }
        public static string Spreadsheet_Top10Filter { get { return ResourceManager.GetString("Spreadsheet_Top10Filter", resourceCulture); } }
        public static string Spreadsheet_Top10FilterTooltip { get { return ResourceManager.GetString("Spreadsheet_Top10FilterTooltip", resourceCulture); } }
        public static string Spreadsheet_Top10Show { get { return ResourceManager.GetString("Spreadsheet_Top10Show", resourceCulture); } }
        public static string Spreadsheet_Top10DirectionTop { get { return ResourceManager.GetString("Spreadsheet_Top10DirectionTop", resourceCulture); } }
        public static string Spreadsheet_Top10DirectionBottom { get { return ResourceManager.GetString("Spreadsheet_Top10DirectionBottom", resourceCulture); } }
        public static string Spreadsheet_Top10UnitItems { get { return ResourceManager.GetString("Spreadsheet_Top10UnitItems", resourceCulture); } }
        public static string Spreadsheet_Top10UnitPercent { get { return ResourceManager.GetString("Spreadsheet_Top10UnitPercent", resourceCulture); } }
        public static string Spreadsheet_FilterAboveAverage { get { return ResourceManager.GetString("Spreadsheet_FilterAboveAverage", resourceCulture); } }
        public static string Spreadsheet_FilterBelowAverage { get { return ResourceManager.GetString("Spreadsheet_FilterBelowAverage", resourceCulture); } }
        public static string DropDown_RemoveChipTitle { get { return ResourceManager.GetString("DropDown_RemoveChipTitle", resourceCulture); } }
        public static string DropDown_ClearAriaLabel { get { return ResourceManager.GetString("DropDown_ClearAriaLabel", resourceCulture); } }
        public static string DropDown_SearchAriaLabel { get { return ResourceManager.GetString("DropDown_SearchAriaLabel", resourceCulture); } }
        public static string DropDown_EmptyAriaLabel { get { return ResourceManager.GetString("DropDown_EmptyAriaLabel", resourceCulture); } }
        public static string AIChat_Placeholder { get { return ResourceManager.GetString("AIChat_Placeholder", resourceCulture); } }
        public static string AIChat_EmptyMessage { get { return ResourceManager.GetString("AIChat_EmptyMessage", resourceCulture); } }
        public static string AIChat_UserAvatarText { get { return ResourceManager.GetString("AIChat_UserAvatarText", resourceCulture); } }
        public static string AIChat_AssistantAvatarText { get { return ResourceManager.GetString("AIChat_AssistantAvatarText", resourceCulture); } }
        public static string Button_ImageAlternateText { get { return ResourceManager.GetString("Button_ImageAlternateText", resourceCulture); } }
        public static string Carousel_PagerButtonAriaLabelFormat { get { return ResourceManager.GetString("Carousel_PagerButtonAriaLabelFormat", resourceCulture); } }
        public static string Chat_Placeholder { get { return ResourceManager.GetString("Chat_Placeholder", resourceCulture); } }
        public static string Chat_EmptyMessage { get { return ResourceManager.GetString("Chat_EmptyMessage", resourceCulture); } }
        public static string Chat_NewMessagesText { get { return ResourceManager.GetString("Chat_NewMessagesText", resourceCulture); } }
        public static string Chip_RemoveChipTitle { get { return ResourceManager.GetString("Chip_RemoveChipTitle", resourceCulture); } }
        public static string ChipList_RemoveChipTitle { get { return ResourceManager.GetString("ChipList_RemoveChipTitle", resourceCulture); } }
        public static string ColorPicker_ToggleAriaLabel { get { return ResourceManager.GetString("ColorPicker_ToggleAriaLabel", resourceCulture); } }
        public static string ColorPicker_PopupAriaLabel { get { return ResourceManager.GetString("ColorPicker_PopupAriaLabel", resourceCulture); } }
        public static string ColorPicker_HexText { get { return ResourceManager.GetString("ColorPicker_HexText", resourceCulture); } }
        public static string ColorPicker_RedText { get { return ResourceManager.GetString("ColorPicker_RedText", resourceCulture); } }
        public static string ColorPicker_GreenText { get { return ResourceManager.GetString("ColorPicker_GreenText", resourceCulture); } }
        public static string ColorPicker_BlueText { get { return ResourceManager.GetString("ColorPicker_BlueText", resourceCulture); } }
        public static string ColorPicker_AlphaText { get { return ResourceManager.GetString("ColorPicker_AlphaText", resourceCulture); } }
        public static string ColorPicker_ButtonText { get { return ResourceManager.GetString("ColorPicker_ButtonText", resourceCulture); } }
        public static string DataAnnotationValidator_MessageSeparator { get { return ResourceManager.GetString("DataAnnotationValidator_MessageSeparator", resourceCulture); } }
        public static string DataFilter_FilterText { get { return ResourceManager.GetString("DataFilter_FilterText", resourceCulture); } }
        public static string DataFilter_EnumFilterSelectText { get { return ResourceManager.GetString("DataFilter_EnumFilterSelectText", resourceCulture); } }
        public static string DataFilter_AndOperatorText { get { return ResourceManager.GetString("DataFilter_AndOperatorText", resourceCulture); } }
        public static string DataFilter_OrOperatorText { get { return ResourceManager.GetString("DataFilter_OrOperatorText", resourceCulture); } }
        public static string DataFilter_ApplyFilterText { get { return ResourceManager.GetString("DataFilter_ApplyFilterText", resourceCulture); } }
        public static string DataFilter_ClearFilterText { get { return ResourceManager.GetString("DataFilter_ClearFilterText", resourceCulture); } }
        public static string DataFilter_AddFilterText { get { return ResourceManager.GetString("DataFilter_AddFilterText", resourceCulture); } }
        public static string DataFilter_RemoveFilterText { get { return ResourceManager.GetString("DataFilter_RemoveFilterText", resourceCulture); } }
        public static string DataFilter_AddFilterGroupText { get { return ResourceManager.GetString("DataFilter_AddFilterGroupText", resourceCulture); } }
        public static string DataFilter_EqualsText { get { return ResourceManager.GetString("DataFilter_EqualsText", resourceCulture); } }
        public static string DataFilter_NotEqualsText { get { return ResourceManager.GetString("DataFilter_NotEqualsText", resourceCulture); } }
        public static string DataFilter_LessThanText { get { return ResourceManager.GetString("DataFilter_LessThanText", resourceCulture); } }
        public static string DataFilter_LessThanOrEqualsText { get { return ResourceManager.GetString("DataFilter_LessThanOrEqualsText", resourceCulture); } }
        public static string DataFilter_GreaterThanText { get { return ResourceManager.GetString("DataFilter_GreaterThanText", resourceCulture); } }
        public static string DataFilter_GreaterThanOrEqualsText { get { return ResourceManager.GetString("DataFilter_GreaterThanOrEqualsText", resourceCulture); } }
        public static string DataFilter_EndsWithText { get { return ResourceManager.GetString("DataFilter_EndsWithText", resourceCulture); } }
        public static string DataFilter_ContainsText { get { return ResourceManager.GetString("DataFilter_ContainsText", resourceCulture); } }
        public static string DataFilter_DoesNotContainText { get { return ResourceManager.GetString("DataFilter_DoesNotContainText", resourceCulture); } }
        public static string DataFilter_InText { get { return ResourceManager.GetString("DataFilter_InText", resourceCulture); } }
        public static string DataFilter_NotInText { get { return ResourceManager.GetString("DataFilter_NotInText", resourceCulture); } }
        public static string DataFilter_StartsWithText { get { return ResourceManager.GetString("DataFilter_StartsWithText", resourceCulture); } }
        public static string DataFilter_IsNotNullText { get { return ResourceManager.GetString("DataFilter_IsNotNullText", resourceCulture); } }
        public static string DataFilter_IsNullText { get { return ResourceManager.GetString("DataFilter_IsNullText", resourceCulture); } }
        public static string DataFilter_IsEmptyText { get { return ResourceManager.GetString("DataFilter_IsEmptyText", resourceCulture); } }
        public static string DataFilter_IsNotEmptyText { get { return ResourceManager.GetString("DataFilter_IsNotEmptyText", resourceCulture); } }
        public static string DataFilter_CustomText { get { return ResourceManager.GetString("DataFilter_CustomText", resourceCulture); } }
        public static string DataGrid_FilterText { get { return ResourceManager.GetString("DataGrid_FilterText", resourceCulture); } }
        public static string DataGrid_EnumFilterSelectText { get { return ResourceManager.GetString("DataGrid_EnumFilterSelectText", resourceCulture); } }
        public static string DataGrid_EnumNullFilterText { get { return ResourceManager.GetString("DataGrid_EnumNullFilterText", resourceCulture); } }
        public static string DataGrid_AndOperatorText { get { return ResourceManager.GetString("DataGrid_AndOperatorText", resourceCulture); } }
        public static string DataGrid_OrOperatorText { get { return ResourceManager.GetString("DataGrid_OrOperatorText", resourceCulture); } }
        public static string DataGrid_ApplyFilterText { get { return ResourceManager.GetString("DataGrid_ApplyFilterText", resourceCulture); } }
        public static string DataGrid_ClearFilterText { get { return ResourceManager.GetString("DataGrid_ClearFilterText", resourceCulture); } }
        public static string DataGrid_EqualsText { get { return ResourceManager.GetString("DataGrid_EqualsText", resourceCulture); } }
        public static string DataGrid_NotEqualsText { get { return ResourceManager.GetString("DataGrid_NotEqualsText", resourceCulture); } }
        public static string DataGrid_LessThanText { get { return ResourceManager.GetString("DataGrid_LessThanText", resourceCulture); } }
        public static string DataGrid_LessThanOrEqualsText { get { return ResourceManager.GetString("DataGrid_LessThanOrEqualsText", resourceCulture); } }
        public static string DataGrid_GreaterThanText { get { return ResourceManager.GetString("DataGrid_GreaterThanText", resourceCulture); } }
        public static string DataGrid_GreaterThanOrEqualsText { get { return ResourceManager.GetString("DataGrid_GreaterThanOrEqualsText", resourceCulture); } }
        public static string DataGrid_EndsWithText { get { return ResourceManager.GetString("DataGrid_EndsWithText", resourceCulture); } }
        public static string DataGrid_ContainsText { get { return ResourceManager.GetString("DataGrid_ContainsText", resourceCulture); } }
        public static string DataGrid_DoesNotContainText { get { return ResourceManager.GetString("DataGrid_DoesNotContainText", resourceCulture); } }
        public static string DataGrid_InText { get { return ResourceManager.GetString("DataGrid_InText", resourceCulture); } }
        public static string DataGrid_NotInText { get { return ResourceManager.GetString("DataGrid_NotInText", resourceCulture); } }
        public static string DataGrid_StartsWithText { get { return ResourceManager.GetString("DataGrid_StartsWithText", resourceCulture); } }
        public static string DataGrid_IsNotNullText { get { return ResourceManager.GetString("DataGrid_IsNotNullText", resourceCulture); } }
        public static string DataGrid_IsNullText { get { return ResourceManager.GetString("DataGrid_IsNullText", resourceCulture); } }
        public static string DataGrid_IsEmptyText { get { return ResourceManager.GetString("DataGrid_IsEmptyText", resourceCulture); } }
        public static string DataGrid_IsNotEmptyText { get { return ResourceManager.GetString("DataGrid_IsNotEmptyText", resourceCulture); } }
        public static string DataGrid_CustomText { get { return ResourceManager.GetString("DataGrid_CustomText", resourceCulture); } }
        public static string DataGrid_ColumnsShowingText { get { return ResourceManager.GetString("DataGrid_ColumnsShowingText", resourceCulture); } }
        public static string DataGrid_AllColumnsText { get { return ResourceManager.GetString("DataGrid_AllColumnsText", resourceCulture); } }
        public static string DataGrid_ColumnsText { get { return ResourceManager.GetString("DataGrid_ColumnsText", resourceCulture); } }
        public static string DataGrid_RemoveGroupAriaLabel { get { return ResourceManager.GetString("DataGrid_RemoveGroupAriaLabel", resourceCulture); } }
        public static string DataGrid_SelectVisibleColumnsAriaLabel { get { return ResourceManager.GetString("DataGrid_SelectVisibleColumnsAriaLabel", resourceCulture); } }
        public static string DataGrid_LogicalOperatorAriaLabel { get { return ResourceManager.GetString("DataGrid_LogicalOperatorAriaLabel", resourceCulture); } }
        public static string DataGrid_FilterOperatorAriaLabel { get { return ResourceManager.GetString("DataGrid_FilterOperatorAriaLabel", resourceCulture); } }
        public static string DataGrid_SecondFilterOperatorAriaLabel { get { return ResourceManager.GetString("DataGrid_SecondFilterOperatorAriaLabel", resourceCulture); } }
        public static string DataGrid_FilterValueAriaLabel { get { return ResourceManager.GetString("DataGrid_FilterValueAriaLabel", resourceCulture); } }
        public static string DataGrid_SecondFilterValueAriaLabel { get { return ResourceManager.GetString("DataGrid_SecondFilterValueAriaLabel", resourceCulture); } }
        public static string DataGrid_GroupPanelText { get { return ResourceManager.GetString("DataGrid_GroupPanelText", resourceCulture); } }
        public static string DataGrid_ExpandAllTitle { get { return ResourceManager.GetString("DataGrid_ExpandAllTitle", resourceCulture); } }
        public static string DataGrid_CollapseAllTitle { get { return ResourceManager.GetString("DataGrid_CollapseAllTitle", resourceCulture); } }
        public static string DatePicker_CalendarWeekTitle { get { return ResourceManager.GetString("DatePicker_CalendarWeekTitle", resourceCulture); } }
        public static string DatePicker_ToggleAriaLabel { get { return ResourceManager.GetString("DatePicker_ToggleAriaLabel", resourceCulture); } }
        public static string DatePicker_PopupAriaLabel { get { return ResourceManager.GetString("DatePicker_PopupAriaLabel", resourceCulture); } }
        public static string DatePicker_ClearAriaLabel { get { return ResourceManager.GetString("DatePicker_ClearAriaLabel", resourceCulture); } }
        public static string DatePicker_HourAriaLabel { get { return ResourceManager.GetString("DatePicker_HourAriaLabel", resourceCulture); } }
        public static string DatePicker_MinutesAriaLabel { get { return ResourceManager.GetString("DatePicker_MinutesAriaLabel", resourceCulture); } }
        public static string DatePicker_SecondsAriaLabel { get { return ResourceManager.GetString("DatePicker_SecondsAriaLabel", resourceCulture); } }
        public static string DatePicker_OkAriaLabel { get { return ResourceManager.GetString("DatePicker_OkAriaLabel", resourceCulture); } }
        public static string DatePicker_PrevMonthAriaLabel { get { return ResourceManager.GetString("DatePicker_PrevMonthAriaLabel", resourceCulture); } }
        public static string DatePicker_NextMonthAriaLabel { get { return ResourceManager.GetString("DatePicker_NextMonthAriaLabel", resourceCulture); } }
        public static string DatePicker_ToggleAmPmAriaLabel { get { return ResourceManager.GetString("DatePicker_ToggleAmPmAriaLabel", resourceCulture); } }
        public static string DropDown_SelectedItemsText { get { return ResourceManager.GetString("DropDown_SelectedItemsText", resourceCulture); } }
        public static string DropDownDataGrid_PagingSummaryFormat { get { return ResourceManager.GetString("DropDownDataGrid_PagingSummaryFormat", resourceCulture); } }
        public static string DropDownDataGrid_FirstPageTitle { get { return ResourceManager.GetString("DropDownDataGrid_FirstPageTitle", resourceCulture); } }
        public static string DropDownDataGrid_FirstPageAriaLabel { get { return ResourceManager.GetString("DropDownDataGrid_FirstPageAriaLabel", resourceCulture); } }
        public static string DropDownDataGrid_PrevPageTitle { get { return ResourceManager.GetString("DropDownDataGrid_PrevPageTitle", resourceCulture); } }
        public static string DropDownDataGrid_PrevPageAriaLabel { get { return ResourceManager.GetString("DropDownDataGrid_PrevPageAriaLabel", resourceCulture); } }
        public static string DropDownDataGrid_LastPageTitle { get { return ResourceManager.GetString("DropDownDataGrid_LastPageTitle", resourceCulture); } }
        public static string DropDownDataGrid_LastPageAriaLabel { get { return ResourceManager.GetString("DropDownDataGrid_LastPageAriaLabel", resourceCulture); } }
        public static string DropDownDataGrid_NextPageTitle { get { return ResourceManager.GetString("DropDownDataGrid_NextPageTitle", resourceCulture); } }
        public static string DropDownDataGrid_NextPageAriaLabel { get { return ResourceManager.GetString("DropDownDataGrid_NextPageAriaLabel", resourceCulture); } }
        public static string DropDownDataGrid_PageTitleFormat { get { return ResourceManager.GetString("DropDownDataGrid_PageTitleFormat", resourceCulture); } }
        public static string DropDownDataGrid_PageAriaLabelFormat { get { return ResourceManager.GetString("DropDownDataGrid_PageAriaLabelFormat", resourceCulture); } }
        public static string DropDownDataGrid_EmptyText { get { return ResourceManager.GetString("DropDownDataGrid_EmptyText", resourceCulture); } }
        public static string DropDownDataGrid_SearchTextPlaceholder { get { return ResourceManager.GetString("DropDownDataGrid_SearchTextPlaceholder", resourceCulture); } }
        public static string DropDownDataGrid_AddAriaLabel { get { return ResourceManager.GetString("DropDownDataGrid_AddAriaLabel", resourceCulture); } }
        public static string DropDownDataGrid_SelectedItemsText { get { return ResourceManager.GetString("DropDownDataGrid_SelectedItemsText", resourceCulture); } }
        public static string FileInput_ChooseText { get { return ResourceManager.GetString("FileInput_ChooseText", resourceCulture); } }
        public static string FileInput_DeleteText { get { return ResourceManager.GetString("FileInput_DeleteText", resourceCulture); } }
        public static string FileInput_ImageAlternateText { get { return ResourceManager.GetString("FileInput_ImageAlternateText", resourceCulture); } }
        public static string Gantt_TodayText { get { return ResourceManager.GetString("Gantt_TodayText", resourceCulture); } }
        public static string Gantt_PrevText { get { return ResourceManager.GetString("Gantt_PrevText", resourceCulture); } }
        public static string Gantt_NextText { get { return ResourceManager.GetString("Gantt_NextText", resourceCulture); } }
        public static string Gantt_ZoomToFitText { get { return ResourceManager.GetString("Gantt_ZoomToFitText", resourceCulture); } }
        public static string Gantt_EmptyText { get { return ResourceManager.GetString("Gantt_EmptyText", resourceCulture); } }
        public static string Gantt_FilterText { get { return ResourceManager.GetString("Gantt_FilterText", resourceCulture); } }
        public static string Gantt_AndOperatorText { get { return ResourceManager.GetString("Gantt_AndOperatorText", resourceCulture); } }
        public static string Gantt_OrOperatorText { get { return ResourceManager.GetString("Gantt_OrOperatorText", resourceCulture); } }
        public static string Gantt_ApplyFilterText { get { return ResourceManager.GetString("Gantt_ApplyFilterText", resourceCulture); } }
        public static string Gantt_ClearFilterText { get { return ResourceManager.GetString("Gantt_ClearFilterText", resourceCulture); } }
        public static string Gantt_EqualsText { get { return ResourceManager.GetString("Gantt_EqualsText", resourceCulture); } }
        public static string Gantt_NotEqualsText { get { return ResourceManager.GetString("Gantt_NotEqualsText", resourceCulture); } }
        public static string Gantt_LessThanText { get { return ResourceManager.GetString("Gantt_LessThanText", resourceCulture); } }
        public static string Gantt_LessThanOrEqualsText { get { return ResourceManager.GetString("Gantt_LessThanOrEqualsText", resourceCulture); } }
        public static string Gantt_GreaterThanText { get { return ResourceManager.GetString("Gantt_GreaterThanText", resourceCulture); } }
        public static string Gantt_GreaterThanOrEqualsText { get { return ResourceManager.GetString("Gantt_GreaterThanOrEqualsText", resourceCulture); } }
        public static string Gantt_ContainsText { get { return ResourceManager.GetString("Gantt_ContainsText", resourceCulture); } }
        public static string Gantt_DoesNotContainText { get { return ResourceManager.GetString("Gantt_DoesNotContainText", resourceCulture); } }
        public static string Gantt_StartsWithText { get { return ResourceManager.GetString("Gantt_StartsWithText", resourceCulture); } }
        public static string Gantt_EndsWithText { get { return ResourceManager.GetString("Gantt_EndsWithText", resourceCulture); } }
        public static string Gantt_IsNullText { get { return ResourceManager.GetString("Gantt_IsNullText", resourceCulture); } }
        public static string Gantt_IsNotNullText { get { return ResourceManager.GetString("Gantt_IsNotNullText", resourceCulture); } }
        public static string Gantt_IsEmptyText { get { return ResourceManager.GetString("Gantt_IsEmptyText", resourceCulture); } }
        public static string Gantt_IsNotEmptyText { get { return ResourceManager.GetString("Gantt_IsNotEmptyText", resourceCulture); } }
        public static string Gravatar_AlternateText { get { return ResourceManager.GetString("Gravatar_AlternateText", resourceCulture); } }
        public static string HtmlEditorAlignCenter_Title { get { return ResourceManager.GetString("HtmlEditorAlignCenter_Title", resourceCulture); } }
        public static string HtmlEditorAlignLeft_Title { get { return ResourceManager.GetString("HtmlEditorAlignLeft_Title", resourceCulture); } }
        public static string HtmlEditorAlignRight_Title { get { return ResourceManager.GetString("HtmlEditorAlignRight_Title", resourceCulture); } }
        public static string HtmlEditorBackground_Title { get { return ResourceManager.GetString("HtmlEditorBackground_Title", resourceCulture); } }
        public static string HtmlEditorBold_Title { get { return ResourceManager.GetString("HtmlEditorBold_Title", resourceCulture); } }
        public static string HtmlEditorColor_Title { get { return ResourceManager.GetString("HtmlEditorColor_Title", resourceCulture); } }
        public static string HtmlEditorColor_HexText { get { return ResourceManager.GetString("HtmlEditorColor_HexText", resourceCulture); } }
        public static string HtmlEditorColor_RedText { get { return ResourceManager.GetString("HtmlEditorColor_RedText", resourceCulture); } }
        public static string HtmlEditorColor_GreenText { get { return ResourceManager.GetString("HtmlEditorColor_GreenText", resourceCulture); } }
        public static string HtmlEditorColor_BlueText { get { return ResourceManager.GetString("HtmlEditorColor_BlueText", resourceCulture); } }
        public static string HtmlEditorColor_AlphaText { get { return ResourceManager.GetString("HtmlEditorColor_AlphaText", resourceCulture); } }
        public static string HtmlEditorColor_ButtonText { get { return ResourceManager.GetString("HtmlEditorColor_ButtonText", resourceCulture); } }
        public static string HtmlEditorFontName_Placeholder { get { return ResourceManager.GetString("HtmlEditorFontName_Placeholder", resourceCulture); } }
        public static string HtmlEditorFontName_Title { get { return ResourceManager.GetString("HtmlEditorFontName_Title", resourceCulture); } }
        public static string HtmlEditorFontSize_Placeholder { get { return ResourceManager.GetString("HtmlEditorFontSize_Placeholder", resourceCulture); } }
        public static string HtmlEditorFontSize_Title { get { return ResourceManager.GetString("HtmlEditorFontSize_Title", resourceCulture); } }
        public static string HtmlEditorImage_Title { get { return ResourceManager.GetString("HtmlEditorImage_Title", resourceCulture); } }
        public static string HtmlEditorImage_SelectText { get { return ResourceManager.GetString("HtmlEditorImage_SelectText", resourceCulture); } }
        public static string HtmlEditorImage_UploadChooseText { get { return ResourceManager.GetString("HtmlEditorImage_UploadChooseText", resourceCulture); } }
        public static string HtmlEditorImage_UrlText { get { return ResourceManager.GetString("HtmlEditorImage_UrlText", resourceCulture); } }
        public static string HtmlEditorImage_AltText { get { return ResourceManager.GetString("HtmlEditorImage_AltText", resourceCulture); } }
        public static string HtmlEditorImage_OkText { get { return ResourceManager.GetString("HtmlEditorImage_OkText", resourceCulture); } }
        public static string HtmlEditorImage_CancelText { get { return ResourceManager.GetString("HtmlEditorImage_CancelText", resourceCulture); } }
        public static string HtmlEditorImage_WidthText { get { return ResourceManager.GetString("HtmlEditorImage_WidthText", resourceCulture); } }
        public static string HtmlEditorImage_HeightText { get { return ResourceManager.GetString("HtmlEditorImage_HeightText", resourceCulture); } }
        public static string HtmlEditorIndent_Title { get { return ResourceManager.GetString("HtmlEditorIndent_Title", resourceCulture); } }
        public static string HtmlEditorItalic_Title { get { return ResourceManager.GetString("HtmlEditorItalic_Title", resourceCulture); } }
        public static string HtmlEditorJustify_Title { get { return ResourceManager.GetString("HtmlEditorJustify_Title", resourceCulture); } }
        public static string HtmlEditorLink_Title { get { return ResourceManager.GetString("HtmlEditorLink_Title", resourceCulture); } }
        public static string HtmlEditorLink_UrlText { get { return ResourceManager.GetString("HtmlEditorLink_UrlText", resourceCulture); } }
        public static string HtmlEditorLink_OpenInNewWindowText { get { return ResourceManager.GetString("HtmlEditorLink_OpenInNewWindowText", resourceCulture); } }
        public static string HtmlEditorLink_LinkText { get { return ResourceManager.GetString("HtmlEditorLink_LinkText", resourceCulture); } }
        public static string HtmlEditorLink_OkText { get { return ResourceManager.GetString("HtmlEditorLink_OkText", resourceCulture); } }
        public static string HtmlEditorLink_CancelText { get { return ResourceManager.GetString("HtmlEditorLink_CancelText", resourceCulture); } }
        public static string HtmlEditorOrderedList_Title { get { return ResourceManager.GetString("HtmlEditorOrderedList_Title", resourceCulture); } }
        public static string HtmlEditorOutdent_Title { get { return ResourceManager.GetString("HtmlEditorOutdent_Title", resourceCulture); } }
        public static string HtmlEditorRedo_Title { get { return ResourceManager.GetString("HtmlEditorRedo_Title", resourceCulture); } }
        public static string HtmlEditorRemoveFormat_Title { get { return ResourceManager.GetString("HtmlEditorRemoveFormat_Title", resourceCulture); } }
        public static string HtmlEditorSource_Title { get { return ResourceManager.GetString("HtmlEditorSource_Title", resourceCulture); } }
        public static string HtmlEditorStrikeThrough_Title { get { return ResourceManager.GetString("HtmlEditorStrikeThrough_Title", resourceCulture); } }
        public static string HtmlEditorSubscript_Title { get { return ResourceManager.GetString("HtmlEditorSubscript_Title", resourceCulture); } }
        public static string HtmlEditorSuperscript_Title { get { return ResourceManager.GetString("HtmlEditorSuperscript_Title", resourceCulture); } }
        public static string HtmlEditorUnderline_Title { get { return ResourceManager.GetString("HtmlEditorUnderline_Title", resourceCulture); } }
        public static string HtmlEditorUndo_Title { get { return ResourceManager.GetString("HtmlEditorUndo_Title", resourceCulture); } }
        public static string HtmlEditorUnlink_Title { get { return ResourceManager.GetString("HtmlEditorUnlink_Title", resourceCulture); } }
        public static string HtmlEditorUnorderedList_Title { get { return ResourceManager.GetString("HtmlEditorUnorderedList_Title", resourceCulture); } }
        public static string Image_AlternateText { get { return ResourceManager.GetString("Image_AlternateText", resourceCulture); } }
        public static string Link_ImageAlternateText { get { return ResourceManager.GetString("Link_ImageAlternateText", resourceCulture); } }
        public static string ListBox_EmptyText { get { return ResourceManager.GetString("ListBox_EmptyText", resourceCulture); } }
        public static string Login_LoginText { get { return ResourceManager.GetString("Login_LoginText", resourceCulture); } }
        public static string Login_RegisterText { get { return ResourceManager.GetString("Login_RegisterText", resourceCulture); } }
        public static string Login_RememberMeText { get { return ResourceManager.GetString("Login_RememberMeText", resourceCulture); } }
        public static string Login_RegisterMessageText { get { return ResourceManager.GetString("Login_RegisterMessageText", resourceCulture); } }
        public static string Login_ResetPasswordText { get { return ResourceManager.GetString("Login_ResetPasswordText", resourceCulture); } }
        public static string Login_UserText { get { return ResourceManager.GetString("Login_UserText", resourceCulture); } }
        public static string Login_UserRequired { get { return ResourceManager.GetString("Login_UserRequired", resourceCulture); } }
        public static string Login_PasswordText { get { return ResourceManager.GetString("Login_PasswordText", resourceCulture); } }
        public static string Login_PasswordRequired { get { return ResourceManager.GetString("Login_PasswordRequired", resourceCulture); } }
        public static string Menu_AriaLabel { get { return ResourceManager.GetString("Menu_AriaLabel", resourceCulture); } }
        public static string Menu_ToggleAriaLabel { get { return ResourceManager.GetString("Menu_ToggleAriaLabel", resourceCulture); } }
        public static string MenuItem_ImageAlternateText { get { return ResourceManager.GetString("MenuItem_ImageAlternateText", resourceCulture); } }
        public static string MonthView_MoreText { get { return ResourceManager.GetString("MonthView_MoreText", resourceCulture); } }
        public static string Numeric_UpAriaLabel { get { return ResourceManager.GetString("Numeric_UpAriaLabel", resourceCulture); } }
        public static string Numeric_DownAriaLabel { get { return ResourceManager.GetString("Numeric_DownAriaLabel", resourceCulture); } }
        public static string Pager_FirstPageTitle { get { return ResourceManager.GetString("Pager_FirstPageTitle", resourceCulture); } }
        public static string Pager_FirstPageAriaLabel { get { return ResourceManager.GetString("Pager_FirstPageAriaLabel", resourceCulture); } }
        public static string Pager_PrevPageTitle { get { return ResourceManager.GetString("Pager_PrevPageTitle", resourceCulture); } }
        public static string Pager_PrevPageAriaLabel { get { return ResourceManager.GetString("Pager_PrevPageAriaLabel", resourceCulture); } }
        public static string Pager_LastPageTitle { get { return ResourceManager.GetString("Pager_LastPageTitle", resourceCulture); } }
        public static string Pager_LastPageAriaLabel { get { return ResourceManager.GetString("Pager_LastPageAriaLabel", resourceCulture); } }
        public static string Pager_NextPageTitle { get { return ResourceManager.GetString("Pager_NextPageTitle", resourceCulture); } }
        public static string Pager_NextPageAriaLabel { get { return ResourceManager.GetString("Pager_NextPageAriaLabel", resourceCulture); } }
        public static string Pager_PageTitleFormat { get { return ResourceManager.GetString("Pager_PageTitleFormat", resourceCulture); } }
        public static string Pager_PageAriaLabelFormat { get { return ResourceManager.GetString("Pager_PageAriaLabelFormat", resourceCulture); } }
        public static string Pager_PageSizeText { get { return ResourceManager.GetString("Pager_PageSizeText", resourceCulture); } }
        public static string Pager_NavigationAriaLabel { get { return ResourceManager.GetString("Pager_NavigationAriaLabel", resourceCulture); } }
        public static string Pager_PagingSummaryFormat { get { return ResourceManager.GetString("Pager_PagingSummaryFormat", resourceCulture); } }
        public static string Panel_ExpandTitle { get { return ResourceManager.GetString("Panel_ExpandTitle", resourceCulture); } }
        public static string Panel_CollapseTitle { get { return ResourceManager.GetString("Panel_CollapseTitle", resourceCulture); } }
        public static string PanelMenu_AriaLabel { get { return ResourceManager.GetString("PanelMenu_AriaLabel", resourceCulture); } }
        public static string PanelMenuItem_ImageAlternateText { get { return ResourceManager.GetString("PanelMenuItem_ImageAlternateText", resourceCulture); } }
        public static string PickList_EmptyText { get { return ResourceManager.GetString("PickList_EmptyText", resourceCulture); } }
        public static string PickList_SourceToTargetTitle { get { return ResourceManager.GetString("PickList_SourceToTargetTitle", resourceCulture); } }
        public static string PickList_SelectedSourceToTargetTitle { get { return ResourceManager.GetString("PickList_SelectedSourceToTargetTitle", resourceCulture); } }
        public static string PickList_TargetToSourceTitle { get { return ResourceManager.GetString("PickList_TargetToSourceTitle", resourceCulture); } }
        public static string PickList_SelectedTargetToSourceTitle { get { return ResourceManager.GetString("PickList_SelectedTargetToSourceTitle", resourceCulture); } }
        public static string PivotDataGrid_EmptyText { get { return ResourceManager.GetString("PivotDataGrid_EmptyText", resourceCulture); } }
        public static string PivotDataGrid_FieldsPickerHeaderText { get { return ResourceManager.GetString("PivotDataGrid_FieldsPickerHeaderText", resourceCulture); } }
        public static string PivotDataGrid_RowsText { get { return ResourceManager.GetString("PivotDataGrid_RowsText", resourceCulture); } }
        public static string PivotDataGrid_ColumnsText { get { return ResourceManager.GetString("PivotDataGrid_ColumnsText", resourceCulture); } }
        public static string PivotDataGrid_AggregatesText { get { return ResourceManager.GetString("PivotDataGrid_AggregatesText", resourceCulture); } }
        public static string PivotDataGrid_SortAriaLabelFormat { get { return ResourceManager.GetString("PivotDataGrid_SortAriaLabelFormat", resourceCulture); } }
        public static string PivotDataGrid_FilterText { get { return ResourceManager.GetString("PivotDataGrid_FilterText", resourceCulture); } }
        public static string PivotDataGrid_EnumFilterSelectText { get { return ResourceManager.GetString("PivotDataGrid_EnumFilterSelectText", resourceCulture); } }
        public static string PivotDataGrid_ApplyText { get { return ResourceManager.GetString("PivotDataGrid_ApplyText", resourceCulture); } }
        public static string PivotDataGrid_ClearText { get { return ResourceManager.GetString("PivotDataGrid_ClearText", resourceCulture); } }
        public static string PivotDataGrid_FilterOperatorAriaLabel { get { return ResourceManager.GetString("PivotDataGrid_FilterOperatorAriaLabel", resourceCulture); } }
        public static string PivotDataGrid_FilterValueAriaLabel { get { return ResourceManager.GetString("PivotDataGrid_FilterValueAriaLabel", resourceCulture); } }
        public static string PivotDataGrid_SecondFilterOperatorAriaLabel { get { return ResourceManager.GetString("PivotDataGrid_SecondFilterOperatorAriaLabel", resourceCulture); } }
        public static string PivotDataGrid_SecondFilterValueAriaLabel { get { return ResourceManager.GetString("PivotDataGrid_SecondFilterValueAriaLabel", resourceCulture); } }
        public static string PivotDataGrid_LogicalOperatorAriaLabel { get { return ResourceManager.GetString("PivotDataGrid_LogicalOperatorAriaLabel", resourceCulture); } }
        public static string PivotDataGrid_AndOperatorText { get { return ResourceManager.GetString("PivotDataGrid_AndOperatorText", resourceCulture); } }
        public static string PivotDataGrid_OrOperatorText { get { return ResourceManager.GetString("PivotDataGrid_OrOperatorText", resourceCulture); } }
        public static string PivotDataGrid_EqualsText { get { return ResourceManager.GetString("PivotDataGrid_EqualsText", resourceCulture); } }
        public static string PivotDataGrid_NotEqualsText { get { return ResourceManager.GetString("PivotDataGrid_NotEqualsText", resourceCulture); } }
        public static string PivotDataGrid_LessThanText { get { return ResourceManager.GetString("PivotDataGrid_LessThanText", resourceCulture); } }
        public static string PivotDataGrid_LessThanOrEqualsText { get { return ResourceManager.GetString("PivotDataGrid_LessThanOrEqualsText", resourceCulture); } }
        public static string PivotDataGrid_GreaterThanText { get { return ResourceManager.GetString("PivotDataGrid_GreaterThanText", resourceCulture); } }
        public static string PivotDataGrid_GreaterThanOrEqualsText { get { return ResourceManager.GetString("PivotDataGrid_GreaterThanOrEqualsText", resourceCulture); } }
        public static string PivotDataGrid_EndsWithText { get { return ResourceManager.GetString("PivotDataGrid_EndsWithText", resourceCulture); } }
        public static string PivotDataGrid_ContainsText { get { return ResourceManager.GetString("PivotDataGrid_ContainsText", resourceCulture); } }
        public static string PivotDataGrid_DoesNotContainText { get { return ResourceManager.GetString("PivotDataGrid_DoesNotContainText", resourceCulture); } }
        public static string PivotDataGrid_InText { get { return ResourceManager.GetString("PivotDataGrid_InText", resourceCulture); } }
        public static string PivotDataGrid_NotInText { get { return ResourceManager.GetString("PivotDataGrid_NotInText", resourceCulture); } }
        public static string PivotDataGrid_StartsWithText { get { return ResourceManager.GetString("PivotDataGrid_StartsWithText", resourceCulture); } }
        public static string PivotDataGrid_IsNotNullText { get { return ResourceManager.GetString("PivotDataGrid_IsNotNullText", resourceCulture); } }
        public static string PivotDataGrid_IsNullText { get { return ResourceManager.GetString("PivotDataGrid_IsNullText", resourceCulture); } }
        public static string PivotDataGrid_IsEmptyText { get { return ResourceManager.GetString("PivotDataGrid_IsEmptyText", resourceCulture); } }
        public static string PivotDataGrid_IsNotEmptyText { get { return ResourceManager.GetString("PivotDataGrid_IsNotEmptyText", resourceCulture); } }
        public static string PivotDataGrid_CustomText { get { return ResourceManager.GetString("PivotDataGrid_CustomText", resourceCulture); } }
        public static string ProfileMenu_ToggleAriaLabel { get { return ResourceManager.GetString("ProfileMenu_ToggleAriaLabel", resourceCulture); } }
        public static string ProfileMenuItem_ImageAlternateText { get { return ResourceManager.GetString("ProfileMenuItem_ImageAlternateText", resourceCulture); } }
        public static string Rating_ClearAriaLabel { get { return ResourceManager.GetString("Rating_ClearAriaLabel", resourceCulture); } }
        public static string Rating_RateAriaLabel { get { return ResourceManager.GetString("Rating_RateAriaLabel", resourceCulture); } }
        public static string SankeyDiagram_ValueText { get { return ResourceManager.GetString("SankeyDiagram_ValueText", resourceCulture); } }
        public static string SankeyDiagram_IncomingText { get { return ResourceManager.GetString("SankeyDiagram_IncomingText", resourceCulture); } }
        public static string SankeyDiagram_OutgoingText { get { return ResourceManager.GetString("SankeyDiagram_OutgoingText", resourceCulture); } }
        public static string SankeyDiagram_FlowText { get { return ResourceManager.GetString("SankeyDiagram_FlowText", resourceCulture); } }
        public static string Scheduler_TodayText { get { return ResourceManager.GetString("Scheduler_TodayText", resourceCulture); } }
        public static string Scheduler_NextText { get { return ResourceManager.GetString("Scheduler_NextText", resourceCulture); } }
        public static string Scheduler_PrevText { get { return ResourceManager.GetString("Scheduler_PrevText", resourceCulture); } }
        public static string SidebarToggle_ToggleAriaLabel { get { return ResourceManager.GetString("SidebarToggle_ToggleAriaLabel", resourceCulture); } }
        public static string SignaturePad_ClearAriaLabel { get { return ResourceManager.GetString("SignaturePad_ClearAriaLabel", resourceCulture); } }
        public static string SpeechToTextButton_Title { get { return ResourceManager.GetString("SpeechToTextButton_Title", resourceCulture); } }
        public static string SpeechToTextButton_StopTitle { get { return ResourceManager.GetString("SpeechToTextButton_StopTitle", resourceCulture); } }
        public static string SplitButton_ImageAlternateText { get { return ResourceManager.GetString("SplitButton_ImageAlternateText", resourceCulture); } }
        public static string SplitButton_OpenAriaLabel { get { return ResourceManager.GetString("SplitButton_OpenAriaLabel", resourceCulture); } }
        public static string SplitButton_ButtonAriaLabel { get { return ResourceManager.GetString("SplitButton_ButtonAriaLabel", resourceCulture); } }
        public static string TimeSpanPicker_TogglePopupAriaLabel { get { return ResourceManager.GetString("TimeSpanPicker_TogglePopupAriaLabel", resourceCulture); } }
        public static string TimeSpanPicker_PopupAriaLabel { get { return ResourceManager.GetString("TimeSpanPicker_PopupAriaLabel", resourceCulture); } }
        public static string TimeSpanPicker_ClearAriaLabel { get { return ResourceManager.GetString("TimeSpanPicker_ClearAriaLabel", resourceCulture); } }
        public static string TimeSpanPicker_ConfirmationButtonText { get { return ResourceManager.GetString("TimeSpanPicker_ConfirmationButtonText", resourceCulture); } }
        public static string TimeSpanPicker_PositiveButtonText { get { return ResourceManager.GetString("TimeSpanPicker_PositiveButtonText", resourceCulture); } }
        public static string TimeSpanPicker_NegativeButtonText { get { return ResourceManager.GetString("TimeSpanPicker_NegativeButtonText", resourceCulture); } }
        public static string TimeSpanPicker_NegativeValueText { get { return ResourceManager.GetString("TimeSpanPicker_NegativeValueText", resourceCulture); } }
        public static string TimeSpanPicker_DaysUnitText { get { return ResourceManager.GetString("TimeSpanPicker_DaysUnitText", resourceCulture); } }
        public static string TimeSpanPicker_HoursUnitText { get { return ResourceManager.GetString("TimeSpanPicker_HoursUnitText", resourceCulture); } }
        public static string TimeSpanPicker_MinutesUnitText { get { return ResourceManager.GetString("TimeSpanPicker_MinutesUnitText", resourceCulture); } }
        public static string TimeSpanPicker_SecondsUnitText { get { return ResourceManager.GetString("TimeSpanPicker_SecondsUnitText", resourceCulture); } }
        public static string TimeSpanPicker_MillisecondsUnitText { get { return ResourceManager.GetString("TimeSpanPicker_MillisecondsUnitText", resourceCulture); } }
        public static string TimeSpanPicker_MicrosecondsUnitText { get { return ResourceManager.GetString("TimeSpanPicker_MicrosecondsUnitText", resourceCulture); } }
        public static string Upload_ImageAlternateText { get { return ResourceManager.GetString("Upload_ImageAlternateText", resourceCulture); } }
        public static string Upload_ChooseText { get { return ResourceManager.GetString("Upload_ChooseText", resourceCulture); } }
        public static string Upload_DeleteText { get { return ResourceManager.GetString("Upload_DeleteText", resourceCulture); } }
        public static string YearPlannerView_MoreText { get { return ResourceManager.GetString("YearPlannerView_MoreText", resourceCulture); } }
        public static string YearTimelineView_MoreText { get { return ResourceManager.GetString("YearTimelineView_MoreText", resourceCulture); } }
        public static string YearView_MoreText { get { return ResourceManager.GetString("YearView_MoreText", resourceCulture); } }
        public static string YearView_NoDayEventsText { get { return ResourceManager.GetString("YearView_NoDayEventsText", resourceCulture); } }
        public static string DataList_EmptyText { get { return ResourceManager.GetString("DataList_EmptyText", resourceCulture); } }
    }
}
