//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS1591

namespace Radzen.Blazor {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RadzenStrings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadzenStrings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Radzen.Blazor.RadzenStrings", typeof(RadzenStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Spreadsheet_FileTab { get { return ResourceManager.GetString("Spreadsheet_FileTab", resourceCulture); } }
        public static string Spreadsheet_HomeTab { get { return ResourceManager.GetString("Spreadsheet_HomeTab", resourceCulture); } }
        public static string Spreadsheet_FormatTab { get { return ResourceManager.GetString("Spreadsheet_FormatTab", resourceCulture); } }
        public static string Spreadsheet_InsertTab { get { return ResourceManager.GetString("Spreadsheet_InsertTab", resourceCulture); } }
        public static string Spreadsheet_ViewTab { get { return ResourceManager.GetString("Spreadsheet_ViewTab", resourceCulture); } }
        public static string Spreadsheet_DataTab { get { return ResourceManager.GetString("Spreadsheet_DataTab", resourceCulture); } }
        public static string Spreadsheet_OK { get { return ResourceManager.GetString("Spreadsheet_OK", resourceCulture); } }
        public static string Spreadsheet_Cancel { get { return ResourceManager.GetString("Spreadsheet_Cancel", resourceCulture); } }
        public static string Spreadsheet_FormatCells { get { return ResourceManager.GetString("Spreadsheet_FormatCells", resourceCulture); } }
        public static string Spreadsheet_Rename { get { return ResourceManager.GetString("Spreadsheet_Rename", resourceCulture); } }
        public static string Spreadsheet_Delete { get { return ResourceManager.GetString("Spreadsheet_Delete", resourceCulture); } }
        public static string Spreadsheet_MoveLeft { get { return ResourceManager.GetString("Spreadsheet_MoveLeft", resourceCulture); } }
        public static string Spreadsheet_MoveRight { get { return ResourceManager.GetString("Spreadsheet_MoveRight", resourceCulture); } }
        public static string Spreadsheet_SortAscending { get { return ResourceManager.GetString("Spreadsheet_SortAscending", resourceCulture); } }
        public static string Spreadsheet_SortDescending { get { return ResourceManager.GetString("Spreadsheet_SortDescending", resourceCulture); } }
        public static string Spreadsheet_ClearFilter { get { return ResourceManager.GetString("Spreadsheet_ClearFilter", resourceCulture); } }
        public static string Spreadsheet_CustomFilter { get { return ResourceManager.GetString("Spreadsheet_CustomFilter", resourceCulture); } }
        public static string Spreadsheet_SelectAll { get { return ResourceManager.GetString("Spreadsheet_SelectAll", resourceCulture); } }
        public static string Spreadsheet_Blank { get { return ResourceManager.GetString("Spreadsheet_Blank", resourceCulture); } }
        public static string Spreadsheet_Cut { get { return ResourceManager.GetString("Spreadsheet_Cut", resourceCulture); } }
        public static string Spreadsheet_Copy { get { return ResourceManager.GetString("Spreadsheet_Copy", resourceCulture); } }
        public static string Spreadsheet_Paste { get { return ResourceManager.GetString("Spreadsheet_Paste", resourceCulture); } }
        public static string Spreadsheet_ClearContents { get { return ResourceManager.GetString("Spreadsheet_ClearContents", resourceCulture); } }
        public static string Spreadsheet_ContextSortAscending { get { return ResourceManager.GetString("Spreadsheet_ContextSortAscending", resourceCulture); } }
        public static string Spreadsheet_ContextSortDescending { get { return ResourceManager.GetString("Spreadsheet_ContextSortDescending", resourceCulture); } }
        public static string Spreadsheet_InsertRowAbove { get { return ResourceManager.GetString("Spreadsheet_InsertRowAbove", resourceCulture); } }
        public static string Spreadsheet_InsertRowBelow { get { return ResourceManager.GetString("Spreadsheet_InsertRowBelow", resourceCulture); } }
        public static string Spreadsheet_DeleteRow { get { return ResourceManager.GetString("Spreadsheet_DeleteRow", resourceCulture); } }
        public static string Spreadsheet_HideRow { get { return ResourceManager.GetString("Spreadsheet_HideRow", resourceCulture); } }
        public static string Spreadsheet_UnhideRow { get { return ResourceManager.GetString("Spreadsheet_UnhideRow", resourceCulture); } }
        public static string Spreadsheet_InsertColumnBefore { get { return ResourceManager.GetString("Spreadsheet_InsertColumnBefore", resourceCulture); } }
        public static string Spreadsheet_InsertColumnAfter { get { return ResourceManager.GetString("Spreadsheet_InsertColumnAfter", resourceCulture); } }
        public static string Spreadsheet_DeleteColumn { get { return ResourceManager.GetString("Spreadsheet_DeleteColumn", resourceCulture); } }
        public static string Spreadsheet_HideColumn { get { return ResourceManager.GetString("Spreadsheet_HideColumn", resourceCulture); } }
        public static string Spreadsheet_UnhideColumn { get { return ResourceManager.GetString("Spreadsheet_UnhideColumn", resourceCulture); } }
        public static string Spreadsheet_RenameSheetTitle { get { return ResourceManager.GetString("Spreadsheet_RenameSheetTitle", resourceCulture); } }
        public static string Spreadsheet_CustomFilterTitle { get { return ResourceManager.GetString("Spreadsheet_CustomFilterTitle", resourceCulture); } }
        public static string Spreadsheet_FormatCellsTitle { get { return ResourceManager.GetString("Spreadsheet_FormatCellsTitle", resourceCulture); } }
        public static string Spreadsheet_InsertHyperlinkTitle { get { return ResourceManager.GetString("Spreadsheet_InsertHyperlinkTitle", resourceCulture); } }
        public static string Spreadsheet_ConditionalFormattingTitle { get { return ResourceManager.GetString("Spreadsheet_ConditionalFormattingTitle", resourceCulture); } }
        public static string Spreadsheet_DataValidationTitle { get { return ResourceManager.GetString("Spreadsheet_DataValidationTitle", resourceCulture); } }
        public static string Spreadsheet_InformationTitle { get { return ResourceManager.GetString("Spreadsheet_InformationTitle", resourceCulture); } }
        public static string Spreadsheet_WarningTitle { get { return ResourceManager.GetString("Spreadsheet_WarningTitle", resourceCulture); } }
        public static string Spreadsheet_InvalidValueTitle { get { return ResourceManager.GetString("Spreadsheet_InvalidValueTitle", resourceCulture); } }
        public static string Spreadsheet_DoYouWantToContinue { get { return ResourceManager.GetString("Spreadsheet_DoYouWantToContinue", resourceCulture); } }
        public static string Spreadsheet_NameCannotBeEmpty { get { return ResourceManager.GetString("Spreadsheet_NameCannotBeEmpty", resourceCulture); } }
        public static string Spreadsheet_SheetNameAlreadyExists { get { return ResourceManager.GetString("Spreadsheet_SheetNameAlreadyExists", resourceCulture); } }
        public static string Spreadsheet_DefaultValidationError { get { return ResourceManager.GetString("Spreadsheet_DefaultValidationError", resourceCulture); } }
        public static string Spreadsheet_ShowRowsWhere { get { return ResourceManager.GetString("Spreadsheet_ShowRowsWhere", resourceCulture); } }
        public static string Spreadsheet_SelectOperator { get { return ResourceManager.GetString("Spreadsheet_SelectOperator", resourceCulture); } }
        public static string Spreadsheet_EnterValue { get { return ResourceManager.GetString("Spreadsheet_EnterValue", resourceCulture); } }
        public static string Spreadsheet_ColumnFormat { get { return ResourceManager.GetString("Spreadsheet_ColumnFormat", resourceCulture); } }
        public static string Spreadsheet_FilterEquals { get { return ResourceManager.GetString("Spreadsheet_FilterEquals", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotEqual { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotEqual", resourceCulture); } }
        public static string Spreadsheet_FilterGreaterThan { get { return ResourceManager.GetString("Spreadsheet_FilterGreaterThan", resourceCulture); } }
        public static string Spreadsheet_FilterGreaterThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_FilterGreaterThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_FilterLessThan { get { return ResourceManager.GetString("Spreadsheet_FilterLessThan", resourceCulture); } }
        public static string Spreadsheet_FilterLessThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_FilterLessThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_FilterBeginsWith { get { return ResourceManager.GetString("Spreadsheet_FilterBeginsWith", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotBeginWith { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotBeginWith", resourceCulture); } }
        public static string Spreadsheet_FilterEndsWith { get { return ResourceManager.GetString("Spreadsheet_FilterEndsWith", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotEndWith { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotEndWith", resourceCulture); } }
        public static string Spreadsheet_FilterContains { get { return ResourceManager.GetString("Spreadsheet_FilterContains", resourceCulture); } }
        public static string Spreadsheet_FilterDoesNotContain { get { return ResourceManager.GetString("Spreadsheet_FilterDoesNotContain", resourceCulture); } }
        public static string Spreadsheet_FilterIsEmpty { get { return ResourceManager.GetString("Spreadsheet_FilterIsEmpty", resourceCulture); } }
        public static string Spreadsheet_FilterIsNotEmpty { get { return ResourceManager.GetString("Spreadsheet_FilterIsNotEmpty", resourceCulture); } }
        public static string Spreadsheet_FilterAnd { get { return ResourceManager.GetString("Spreadsheet_FilterAnd", resourceCulture); } }
        public static string Spreadsheet_FilterOr { get { return ResourceManager.GetString("Spreadsheet_FilterOr", resourceCulture); } }
        public static string Spreadsheet_Sample { get { return ResourceManager.GetString("Spreadsheet_Sample", resourceCulture); } }
        public static string Spreadsheet_DecimalPlaces { get { return ResourceManager.GetString("Spreadsheet_DecimalPlaces", resourceCulture); } }
        public static string Spreadsheet_UseThousandsSeparator { get { return ResourceManager.GetString("Spreadsheet_UseThousandsSeparator", resourceCulture); } }
        public static string Spreadsheet_Symbol { get { return ResourceManager.GetString("Spreadsheet_Symbol", resourceCulture); } }
        public static string Spreadsheet_Type { get { return ResourceManager.GetString("Spreadsheet_Type", resourceCulture); } }
        public static string Spreadsheet_FormatCode { get { return ResourceManager.GetString("Spreadsheet_FormatCode", resourceCulture); } }
        public static string Spreadsheet_Conditional { get { return ResourceManager.GetString("Spreadsheet_Conditional", resourceCulture); } }
        public static string Spreadsheet_GreaterThanMenu { get { return ResourceManager.GetString("Spreadsheet_GreaterThanMenu", resourceCulture); } }
        public static string Spreadsheet_LessThanMenu { get { return ResourceManager.GetString("Spreadsheet_LessThanMenu", resourceCulture); } }
        public static string Spreadsheet_BetweenMenu { get { return ResourceManager.GetString("Spreadsheet_BetweenMenu", resourceCulture); } }
        public static string Spreadsheet_EqualToMenu { get { return ResourceManager.GetString("Spreadsheet_EqualToMenu", resourceCulture); } }
        public static string Spreadsheet_TextContainsMenu { get { return ResourceManager.GetString("Spreadsheet_TextContainsMenu", resourceCulture); } }
        public static string Spreadsheet_RuleType { get { return ResourceManager.GetString("Spreadsheet_RuleType", resourceCulture); } }
        public static string Spreadsheet_Value { get { return ResourceManager.GetString("Spreadsheet_Value", resourceCulture); } }
        public static string Spreadsheet_Minimum { get { return ResourceManager.GetString("Spreadsheet_Minimum", resourceCulture); } }
        public static string Spreadsheet_Maximum { get { return ResourceManager.GetString("Spreadsheet_Maximum", resourceCulture); } }
        public static string Spreadsheet_Text { get { return ResourceManager.GetString("Spreadsheet_Text", resourceCulture); } }
        public static string Spreadsheet_BackgroundColor { get { return ResourceManager.GetString("Spreadsheet_BackgroundColor", resourceCulture); } }
        public static string Spreadsheet_TextColor { get { return ResourceManager.GetString("Spreadsheet_TextColor", resourceCulture); } }
        public static string Spreadsheet_RuleGreaterThan { get { return ResourceManager.GetString("Spreadsheet_RuleGreaterThan", resourceCulture); } }
        public static string Spreadsheet_RuleLessThan { get { return ResourceManager.GetString("Spreadsheet_RuleLessThan", resourceCulture); } }
        public static string Spreadsheet_RuleBetween { get { return ResourceManager.GetString("Spreadsheet_RuleBetween", resourceCulture); } }
        public static string Spreadsheet_RuleEqualTo { get { return ResourceManager.GetString("Spreadsheet_RuleEqualTo", resourceCulture); } }
        public static string Spreadsheet_RuleTextContains { get { return ResourceManager.GetString("Spreadsheet_RuleTextContains", resourceCulture); } }
        public static string Spreadsheet_Validation { get { return ResourceManager.GetString("Spreadsheet_Validation", resourceCulture); } }
        public static string Spreadsheet_DataValidationMenu { get { return ResourceManager.GetString("Spreadsheet_DataValidationMenu", resourceCulture); } }
        public static string Spreadsheet_ClearValidation { get { return ResourceManager.GetString("Spreadsheet_ClearValidation", resourceCulture); } }
        public static string Spreadsheet_ValidationType { get { return ResourceManager.GetString("Spreadsheet_ValidationType", resourceCulture); } }
        public static string Spreadsheet_Operator { get { return ResourceManager.GetString("Spreadsheet_Operator", resourceCulture); } }
        public static string Spreadsheet_Formula { get { return ResourceManager.GetString("Spreadsheet_Formula", resourceCulture); } }
        public static string Spreadsheet_ValuesCommaSeparated { get { return ResourceManager.GetString("Spreadsheet_ValuesCommaSeparated", resourceCulture); } }
        public static string Spreadsheet_AllowBlank { get { return ResourceManager.GetString("Spreadsheet_AllowBlank", resourceCulture); } }
        public static string Spreadsheet_ErrorAlert { get { return ResourceManager.GetString("Spreadsheet_ErrorAlert", resourceCulture); } }
        public static string Spreadsheet_Style { get { return ResourceManager.GetString("Spreadsheet_Style", resourceCulture); } }
        public static string Spreadsheet_Title { get { return ResourceManager.GetString("Spreadsheet_Title", resourceCulture); } }
        public static string Spreadsheet_Message { get { return ResourceManager.GetString("Spreadsheet_Message", resourceCulture); } }
        public static string Spreadsheet_InputPrompt { get { return ResourceManager.GetString("Spreadsheet_InputPrompt", resourceCulture); } }
        public static string Spreadsheet_ShowInputMessage { get { return ResourceManager.GetString("Spreadsheet_ShowInputMessage", resourceCulture); } }
        public static string Spreadsheet_ValidationWholeNumber { get { return ResourceManager.GetString("Spreadsheet_ValidationWholeNumber", resourceCulture); } }
        public static string Spreadsheet_ValidationDecimal { get { return ResourceManager.GetString("Spreadsheet_ValidationDecimal", resourceCulture); } }
        public static string Spreadsheet_ValidationList { get { return ResourceManager.GetString("Spreadsheet_ValidationList", resourceCulture); } }
        public static string Spreadsheet_ValidationDate { get { return ResourceManager.GetString("Spreadsheet_ValidationDate", resourceCulture); } }
        public static string Spreadsheet_ValidationTime { get { return ResourceManager.GetString("Spreadsheet_ValidationTime", resourceCulture); } }
        public static string Spreadsheet_ValidationTextLength { get { return ResourceManager.GetString("Spreadsheet_ValidationTextLength", resourceCulture); } }
        public static string Spreadsheet_ValidationCustom { get { return ResourceManager.GetString("Spreadsheet_ValidationCustom", resourceCulture); } }
        public static string Spreadsheet_OperatorBetween { get { return ResourceManager.GetString("Spreadsheet_OperatorBetween", resourceCulture); } }
        public static string Spreadsheet_OperatorNotBetween { get { return ResourceManager.GetString("Spreadsheet_OperatorNotBetween", resourceCulture); } }
        public static string Spreadsheet_OperatorEqualTo { get { return ResourceManager.GetString("Spreadsheet_OperatorEqualTo", resourceCulture); } }
        public static string Spreadsheet_OperatorNotEqualTo { get { return ResourceManager.GetString("Spreadsheet_OperatorNotEqualTo", resourceCulture); } }
        public static string Spreadsheet_OperatorGreaterThan { get { return ResourceManager.GetString("Spreadsheet_OperatorGreaterThan", resourceCulture); } }
        public static string Spreadsheet_OperatorLessThan { get { return ResourceManager.GetString("Spreadsheet_OperatorLessThan", resourceCulture); } }
        public static string Spreadsheet_OperatorGreaterThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_OperatorGreaterThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_OperatorLessThanOrEqual { get { return ResourceManager.GetString("Spreadsheet_OperatorLessThanOrEqual", resourceCulture); } }
        public static string Spreadsheet_ErrorStyleStop { get { return ResourceManager.GetString("Spreadsheet_ErrorStyleStop", resourceCulture); } }
        public static string Spreadsheet_ErrorStyleWarning { get { return ResourceManager.GetString("Spreadsheet_ErrorStyleWarning", resourceCulture); } }
        public static string Spreadsheet_ErrorStyleInformation { get { return ResourceManager.GetString("Spreadsheet_ErrorStyleInformation", resourceCulture); } }
        public static string Spreadsheet_FreezePanes { get { return ResourceManager.GetString("Spreadsheet_FreezePanes", resourceCulture); } }
        public static string Spreadsheet_FreezeTopRow { get { return ResourceManager.GetString("Spreadsheet_FreezeTopRow", resourceCulture); } }
        public static string Spreadsheet_FreezeSelectedRows { get { return ResourceManager.GetString("Spreadsheet_FreezeSelectedRows", resourceCulture); } }
        public static string Spreadsheet_FreezeFirstColumn { get { return ResourceManager.GetString("Spreadsheet_FreezeFirstColumn", resourceCulture); } }
        public static string Spreadsheet_FreezeSelectedColumns { get { return ResourceManager.GetString("Spreadsheet_FreezeSelectedColumns", resourceCulture); } }
        public static string Spreadsheet_Unfreeze { get { return ResourceManager.GetString("Spreadsheet_Unfreeze", resourceCulture); } }
        public static string Spreadsheet_MergeAndCenter { get { return ResourceManager.GetString("Spreadsheet_MergeAndCenter", resourceCulture); } }
        public static string Spreadsheet_MergeCells { get { return ResourceManager.GetString("Spreadsheet_MergeCells", resourceCulture); } }
        public static string Spreadsheet_UnmergeCells { get { return ResourceManager.GetString("Spreadsheet_UnmergeCells", resourceCulture); } }
        public static string Spreadsheet_AllBorders { get { return ResourceManager.GetString("Spreadsheet_AllBorders", resourceCulture); } }
        public static string Spreadsheet_OutsideBorders { get { return ResourceManager.GetString("Spreadsheet_OutsideBorders", resourceCulture); } }
        public static string Spreadsheet_TopBorder { get { return ResourceManager.GetString("Spreadsheet_TopBorder", resourceCulture); } }
        public static string Spreadsheet_BottomBorder { get { return ResourceManager.GetString("Spreadsheet_BottomBorder", resourceCulture); } }
        public static string Spreadsheet_LeftBorder { get { return ResourceManager.GetString("Spreadsheet_LeftBorder", resourceCulture); } }
        public static string Spreadsheet_RightBorder { get { return ResourceManager.GetString("Spreadsheet_RightBorder", resourceCulture); } }
        public static string Spreadsheet_NoBorder { get { return ResourceManager.GetString("Spreadsheet_NoBorder", resourceCulture); } }
        public static string Spreadsheet_FormatGeneral { get { return ResourceManager.GetString("Spreadsheet_FormatGeneral", resourceCulture); } }
        public static string Spreadsheet_FormatNumber { get { return ResourceManager.GetString("Spreadsheet_FormatNumber", resourceCulture); } }
        public static string Spreadsheet_FormatCurrency { get { return ResourceManager.GetString("Spreadsheet_FormatCurrency", resourceCulture); } }
        public static string Spreadsheet_FormatAccounting { get { return ResourceManager.GetString("Spreadsheet_FormatAccounting", resourceCulture); } }
        public static string Spreadsheet_FormatPercentage { get { return ResourceManager.GetString("Spreadsheet_FormatPercentage", resourceCulture); } }
        public static string Spreadsheet_FormatScientific { get { return ResourceManager.GetString("Spreadsheet_FormatScientific", resourceCulture); } }
        public static string Spreadsheet_FormatDate { get { return ResourceManager.GetString("Spreadsheet_FormatDate", resourceCulture); } }
        public static string Spreadsheet_FormatTime { get { return ResourceManager.GetString("Spreadsheet_FormatTime", resourceCulture); } }
        public static string Spreadsheet_FormatText { get { return ResourceManager.GetString("Spreadsheet_FormatText", resourceCulture); } }
        public static string Spreadsheet_URL { get { return ResourceManager.GetString("Spreadsheet_URL", resourceCulture); } }
        public static string Spreadsheet_DisplayText { get { return ResourceManager.GetString("Spreadsheet_DisplayText", resourceCulture); } }
        public static string Spreadsheet_IncreaseDecimalPlaces { get { return ResourceManager.GetString("Spreadsheet_IncreaseDecimalPlaces", resourceCulture); } }
        public static string Spreadsheet_DecreaseDecimalPlaces { get { return ResourceManager.GetString("Spreadsheet_DecreaseDecimalPlaces", resourceCulture); } }
        public static string Spreadsheet_EditChart { get { return ResourceManager.GetString("Spreadsheet_EditChart", resourceCulture); } }
        public static string Spreadsheet_DeleteChart { get { return ResourceManager.GetString("Spreadsheet_DeleteChart", resourceCulture); } }
        public static string Spreadsheet_EditChartTitle { get { return ResourceManager.GetString("Spreadsheet_EditChartTitle", resourceCulture); } }
        public static string Spreadsheet_ChartType { get { return ResourceManager.GetString("Spreadsheet_ChartType", resourceCulture); } }
        public static string Spreadsheet_ChartTitle { get { return ResourceManager.GetString("Spreadsheet_ChartTitle", resourceCulture); } }
        public static string Spreadsheet_ShowLegend { get { return ResourceManager.GetString("Spreadsheet_ShowLegend", resourceCulture); } }
        public static string Spreadsheet_LegendPosition { get { return ResourceManager.GetString("Spreadsheet_LegendPosition", resourceCulture); } }
        public static string Spreadsheet_Series { get { return ResourceManager.GetString("Spreadsheet_Series", resourceCulture); } }
        public static string Spreadsheet_SeriesColor { get { return ResourceManager.GetString("Spreadsheet_SeriesColor", resourceCulture); } }
        public static string Spreadsheet_CategoryRange { get { return ResourceManager.GetString("Spreadsheet_CategoryRange", resourceCulture); } }
        public static string Spreadsheet_ValueRange { get { return ResourceManager.GetString("Spreadsheet_ValueRange", resourceCulture); } }
        public static string Spreadsheet_InsertHyperlink { get { return ResourceManager.GetString("Spreadsheet_InsertHyperlink", resourceCulture); } }
        public static string Spreadsheet_InsertImage { get { return ResourceManager.GetString("Spreadsheet_InsertImage", resourceCulture); } }
        public static string Spreadsheet_InsertChart { get { return ResourceManager.GetString("Spreadsheet_InsertChart", resourceCulture); } }
    }
}
